//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prism_Library.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.AnInstance = new HashSet<AnInstance>();
        }
    
        public int IDBook { get; set; }
        public int IDAuthor { get; set; }
        public int IDPublishing { get; set; }
        public string Name { get; set; }
        public int Year { get; set; }
        public int IDGenre { get; set; }
        public string InventoryNum { get; set; }
        public Nullable<int> IDInvoice { get; set; }
        public Nullable<int> WriteOffCertificate { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Publishing_House Publishing_House { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnInstance> AnInstance { get; set; }
    }
}
