//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prism_Library.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int IDPassword { get; set; }
        public string Login { get; set; }
        public string Password1 { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    }
}
